site:
  title: Nuvolaris

content:
  sources:
    - url: https://github.com/msciabarra/nuvolaris-documentation
      branches: 0.3.0

ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
